name: flux-plus-pulumi-infra
runtime:
  name: nodejs
  options:
    typescript: false
description: Infrastructure for Flux+Pulumi demo

config:
  bootstrapOrg:
    type: string
    description: The Pulumi org with the bootstrap stack (which creates the cluster etc.)
  repo:
    type: string
    description: The git repo with which to sync, using Flux
  branch:
    type: string
    description: The branch of the repo to sync
    default: main
  targetPath:
    type: string
    description: The path within the repo to sync
    default: sync/
