# This comes almost verbatim from
# https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/wordpress-persistent-disks/wordpress_cloudsql.yaml.template.
# I have modified it to use an env entry for the instance connection
# name argument of the proxy sidecar, rather than substitution; and,
# to change a few names and remove redundant bits.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: 127.0.0.1:3306
          # These secrets are required to start the pod.
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: sql-auth
                key: username
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-auth
                key: password
          ports:
            - containerPort: 80
              name: wordpress
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
          env:
          - name: INSTANCE_CONNECTION_NAME
            valueFrom:
              secretKeyRef:
                name: cloudsql-instance-credentials
                key: instanceConnectionName
          command: ["/cloud_sql_proxy",
                    "-instances=$(INSTANCE_CONNECTION_NAME)=tcp:3306",
                    "-credential_file=/secrets/cloudsql/key.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
