---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pulumi-op
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    semver: 1.11.x
  url: https://github.com/pulumi/pulumi-kubernetes-operator

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pulumi-crds
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: pulumi-op

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pulumi-deploy
  namespace: flux-system
spec:
  dependsOn:
  - name: pulumi-crds
  targetNamespace: default
  interval: 1m0s
  path: ./deploy/yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: pulumi-op

